#BME-230B Spring 2019 Explore Data
Andrew Davidson aedavids@ucsc.edu 

ref:
- [scanpy Single-Cell Analysis in Python doc](https://scanpy.readthedocs.io/en/stable/index.html)
- [annadata: annotated data](https://scanpy.readthedocs.io/en/stable/basic_usage.html#anndata)

## Notes about the data
- The home work says there where two experiments and we need to combine the two data sets. it looks like this was already done for us. Where told "The data has 8098 cells measured on the 3prime platform and 7378 measured on the 5prime platform.

- anndata.X shape:(15476, 1199)
    * 15476 = 8098 + 7378

In [1]:
import numpy as np
import pandas as pd
import scanpy.api as sc

In [2]:
%%time
anndata = sc.read("PBMC.merged.h5ad")
print("adata type:{}".format(type(anndata)))

adata type:<class 'anndata.base.AnnData'>
CPU times: user 1.55 s, sys: 213 ms, total: 1.76 s
Wall time: 1.4 s


In [3]:
anndata

AnnData object with n_obs × n_vars = 15476 × 1199 
    obs: 'Sample', 'n_counts', 'n_genes', 'batch', 'louvain', 'anno', 'Method', 'Cell type'
    var: 'GeneName-0', 'GeneID-0', 'GeneName-1', 'GeneID-1', 'means', 'dispersions', 'dispersions_norm'
    uns: 'Cell type_colors', 'Method_colors', 'Sample_colors', 'anno_colors', 'louvain', 'louvain_colors', 'neighbors', 'rank_genes_groups'
    obsm: 'X_pca', 'X_umap', 'X_tsne'

In [4]:
anndata.X

array([[-0.1964075 ,  2.1636498 , -0.18641369, ..., -0.0779918 ,
        -0.9314647 , -0.77732456],
       [-0.1964075 ,  1.3718529 , -0.18641369, ..., -0.0779918 ,
        -0.9314647 , -0.77732456],
       [-0.1964075 , -0.56439495, -0.18641369, ..., -0.0779918 ,
        -0.9314647 ,  0.8405579 ],
       ...,
       [-0.1964075 , -0.56439495, -0.18641369, ..., -0.0779918 ,
         1.0188808 ,  2.2114685 ],
       [-0.1964075 , -0.56439495, -0.18641369, ..., -0.0779918 ,
         0.5726825 ,  0.21773037],
       [-0.1964075 , -0.56439495, -0.18641369, ..., -0.0779918 ,
         1.1075432 ,  1.8812242 ]], dtype=float32)

In [5]:
print("anndata.X type:{}".format(type(anndata.X)))
print("anndata.X shape:{}".format(anndata.X.shape))

anndata.X type:<class 'numpy.ndarray'>
anndata.X shape:(15476, 1199)


In [6]:
#anndata.uns lots of output

In [7]:
anndata.var.head()

GeneName-0         GeneID-0 GeneName-1         GeneID-1     means  \
index                                                                        
HES4           HES4  ENSG00000188290       HES4  ENSG00000188290  0.114088   
ISG15         ISG15  ENSG00000187608      ISG15  ENSG00000187608  0.589058   
TNFRSF18   TNFRSF18  ENSG00000186891   TNFRSF18  ENSG00000186891  0.088250   
TNFRSF4     TNFRSF4  ENSG00000186827    TNFRSF4  ENSG00000186827  0.123849   
MMP23B       MMP23B  ENSG00000189409     MMP23B  ENSG00000189409  0.046411   

          dispersions  dispersions_norm  
index                                    
HES4         1.479612          1.523847  
ISG15        1.640704          1.394684  
TNFRSF18     1.211858          0.854643  
TNFRSF4      1.205380          0.838453  
MMP23B       1.151547          0.703906

In [8]:
anndata.var.keys()

Index(['GeneName-0', 'GeneID-0', 'GeneName-1', 'GeneID-1', 'means',
       'dispersions', 'dispersions_norm'],
      dtype='object')

In [9]:
anndata.var['GeneName-0'].size

1199

In [10]:
anndata.obs.head()

Sample  n_counts  n_genes batch louvain  \
index                                                                  
data_3p-AAACCTGAGCATCATC-0  data_3p    2394.0      871     0       9   
data_3p-AAACCTGAGCTAGTGG-0  data_3p    4520.0     1316     0       5   
data_3p-AAACCTGCACATTAGC-0  data_3p    2788.0      898     0       1   
data_3p-AAACCTGCACTGTTAG-0  data_3p    4667.0     1526     0       0   
data_3p-AAACCTGCATAGTAAG-0  data_3p    4440.0     1495     0       0   

                                     anno      Method      Cell type  
index                                                                 
data_3p-AAACCTGAGCATCATC-0         B cell  10X_3prime         B cell  
data_3p-AAACCTGAGCTAGTGG-0     CD4 T cell  10X_3prime     CD4 T cell  
data_3p-AAACCTGCACATTAGC-0     CD4 T cell  10X_3prime     CD4 T cell  
data_3p-AAACCTGCACTGTTAG-0  Monocyte_CD14  10X_3prime  Monocyte_CD14  
data_3p-AAACCTGCATAGTAAG-0  Monocyte_CD14  10X_3prime  Monocyte_CD14

In [11]:
anndata.obs.keys()

Index(['Sample', 'n_counts', 'n_genes', 'batch', 'louvain', 'anno', 'Method',
       'Cell type'],
      dtype='object')

In [12]:
anndata.uns.keys()

odict_keys(['Cell type_colors', 'Method_colors', 'Sample_colors', 'anno_colors', 'louvain', 'louvain_colors', 'neighbors', 'rank_genes_groups'])

In [13]:
# type = pandas.core.indexes.base.Index
sum(anndata.obs.index.str.contains('data_3p'))


8098

In [14]:
type(anndata.obs.index)

pandas.core.indexes.base.Index

In [15]:
pd.unique(anndata.obs['Method'])

[10X_3prime, 10X_5prime]
Categories (2, object): [10X_3prime, 10X_5prime]

In [16]:
prime3Rows = anndata.obs['Method'] == '10X_3prime'
prime5Rows = anndata.obs['Method'] == '10X_5prime'
num3PrimeSeries = anndata.obs.loc[prime3Rows, ['n_counts']].count()
num5PrimeSeries = anndata.obs.loc[prime5Rows, ['n_counts']].count()
type(num3PrimeSeries)
print("num 3':{}".format(num3PrimeSeries.values[0]))
print("num 5':{}".format(num5PrimeSeries.values[0]))

num 3':8098
num 5':7378


In [17]:
anndata.obs.loc[prime3Rows].describe()

n_counts      n_genes
count   8098.000000  8098.000000
mean    4741.162598  1429.591875
std     2332.510254   471.849765
min     2002.000000   645.000000
25%     3349.000000  1132.000000
50%     4134.500000  1313.000000
75%     5258.000000  1562.000000
max    31785.000000  4800.000000

In [18]:
type(anndata.X)

foo = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
foo[[0,2], :]

array([[1, 2, 3],
       [7, 8, 9]])

## <span style="color:red">Make sure all the 3 prime cells are stacked on top of the 5 prime cell</span>
this assumption will make the implementation of bb-knn easier

In [19]:
# calc number cells
nCells = anndata.X.shape[0]
print("nCells:{}".format(nCells))

# calc the number of cells in each batch
prime3Rows = anndata.obs['Method'] == '10X_3prime'
prime5Rows = anndata.obs['Method'] == '10X_5prime'

num3PrimeSeries = anndata.obs.loc[prime3Rows, ['n_counts']].count()
num5PrimeSeries = anndata.obs.loc[prime5Rows, ['n_counts']].count()

num3Prime = num3PrimeSeries.values[0]
num5Prime = num5PrimeSeries.values[0]
print("num3Prime':{}".format(num3Prime))
print("num5Prime':{}".format(num5Prime))

assert nCells == (num3Prime + num5Prime)

# create a test data frame
# we assign an index col ordered the way we would expect if the 3prime are stacked on top 
# of the 5 prime
df = pd.DataFrame(data = {'method':anndata.obs['Method'], 
                          'npIdx':[i for i in range(nCells)]
                         })

# check that the npIdx of 3 prime are from zero to num3Prime -1
prime3NpIdx = df.loc[prime3Rows, ['npIdx']].values 
expected3PrimeNpIdx =  np.array( [i for i in range(num3Prime)] ).reshape(prime3NpIdx.shape)

assert (prime3NpIdx == expected3PrimeNpIdx).all()

# check that the npIdx of 5 prime are from num3Prime ... num5Prime - 1
prime5NpIdx = df.loc[prime5Rows, ['npIdx']].values 
start = num3Prime 
end = nCells
expected5PrimeNpIdx =  np.array( [i for i in range(start, end)] )
expected5PrimeNpIdx = expected5PrimeNpIdx.reshape(prime5NpIdx.shape)

assert (prime5NpIdx == expected5PrimeNpIdx).all()


nCells:15476
num3Prime':8098
num5Prime':7378


In [20]:
len(anndata.obs.anno.unique())

9

In [26]:
low = 0
high = low + 5
size = 3 # number of values to generate
np.random.randint(low, high, size)

array([1, 4, 1])

In [27]:
low = 5
high = low + 5
size = 3 # number of values to generate
np.random.randint(low, high, size)

array([9, 6, 8])

In [28]:
np.random.randint(0, 5, 3)

array([4, 0, 3])

In [31]:
x1 = np.array([
    [1, 2],
    [3, 4]
])

x2 = np.array([
    [10, 20],
    [30, 40]
])

byRows = 0
byCols = 1
np.concatenate((x1, x2), axis=byCols)

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40]])