# Explore Data
ref:
- [scanpy Single-Cell Analysis in Python doc](https://scanpy.readthedocs.io/en/stable/index.html)
- [annadata: annotated data](https://scanpy.readthedocs.io/en/stable/basic_usage.html#anndata)

## Notes about the data
- The home work says there where two experiments and we need to combine the two data sets. it looks like this was already done for us. Where told "The data has 8098 cells measured on the 3prime platform and 7378 measured on the 5prime platform.

- anndata.X shape:(15476, 1199)
    * 15476 = 8098 + 7378

In [1]:
import numpy as np
import scanpy.api as sc

In [2]:
%%time
anndata = sc.read("PBMC.merged.h5ad")
print("adata type:{}".format(type(anndata)))

adata type:<class 'anndata.base.AnnData'>
CPU times: user 1.57 s, sys: 193 ms, total: 1.76 s
Wall time: 1.43 s


In [3]:
anndata

AnnData object with n_obs × n_vars = 15476 × 1199 
    obs: 'Sample', 'n_counts', 'n_genes', 'batch', 'louvain', 'anno', 'Method', 'Cell type'
    var: 'GeneName-0', 'GeneID-0', 'GeneName-1', 'GeneID-1', 'means', 'dispersions', 'dispersions_norm'
    uns: 'Cell type_colors', 'Method_colors', 'Sample_colors', 'anno_colors', 'louvain', 'louvain_colors', 'neighbors', 'rank_genes_groups'
    obsm: 'X_pca', 'X_umap', 'X_tsne'

In [4]:
anndata.X

array([[-0.1964075 ,  2.1636498 , -0.18641369, ..., -0.0779918 ,
        -0.9314647 , -0.77732456],
       [-0.1964075 ,  1.3718529 , -0.18641369, ..., -0.0779918 ,
        -0.9314647 , -0.77732456],
       [-0.1964075 , -0.56439495, -0.18641369, ..., -0.0779918 ,
        -0.9314647 ,  0.8405579 ],
       ...,
       [-0.1964075 , -0.56439495, -0.18641369, ..., -0.0779918 ,
         1.0188808 ,  2.2114685 ],
       [-0.1964075 , -0.56439495, -0.18641369, ..., -0.0779918 ,
         0.5726825 ,  0.21773037],
       [-0.1964075 , -0.56439495, -0.18641369, ..., -0.0779918 ,
         1.1075432 ,  1.8812242 ]], dtype=float32)

In [5]:
print("anndata.X type:{}".format(type(anndata.X)))
print("anndata.X shape:{}".format(anndata.X.shape))

anndata.X type:<class 'numpy.ndarray'>
anndata.X shape:(15476, 1199)


In [6]:
#anndata.uns lots of output

In [7]:
anndata.var

GeneName-0         GeneID-0     GeneName-1         GeneID-1  \
index                                                                           
HES4                    HES4  ENSG00000188290           HES4  ENSG00000188290   
ISG15                  ISG15  ENSG00000187608          ISG15  ENSG00000187608   
TNFRSF18            TNFRSF18  ENSG00000186891       TNFRSF18  ENSG00000186891   
TNFRSF4              TNFRSF4  ENSG00000186827        TNFRSF4  ENSG00000186827   
MMP23B                MMP23B  ENSG00000189409         MMP23B  ENSG00000189409   
UTS2                    UTS2  ENSG00000049247           UTS2  ENSG00000049247   
TNFRSF9              TNFRSF9  ENSG00000049249        TNFRSF9  ENSG00000049249   
RBP7                    RBP7  ENSG00000162444           RBP7  ENSG00000162444   
PGD                      PGD  ENSG00000142657            PGD  ENSG00000142657   
AGTRAP                AGTRAP  ENSG00000177674         AGTRAP  ENSG00000177674   
TNFRSF1B            TNFRSF1B  ENSG00000028137       TNFRSF1B  ENSG00000028137   
EFHD2                  EFHD2  ENSG00000142634          EFHD2  ENSG00000142634   
PADI4                  PADI4  ENSG00000159339          PADI4  ENSG00000159339   
CDA                      CDA  ENSG00000158825            CDA  ENSG00000158825   
C1QA                    C1QA  ENSG00000173372           C1QA  ENSG00000173372   
C1QB                    C1QB  ENSG00000173369           C1QB  ENSG00000173369   
ID3                      ID3  ENSG00000117318            ID3  ENSG00000117318   
CNR2                    CNR2  ENSG00000188822           CNR2  ENSG00000188822   
STMN1                  STMN1  ENSG00000117632          STMN1  ENSG00000117632   
ZNF683                ZNF683  ENSG00000176083         ZNF683  ENSG00000176083   
FGR                      FGR  ENSG00000000938            FGR  ENSG00000000938   
IFI6                    IFI6  ENSG00000126709           IFI6  ENSG00000126709   
PTAFR                  PTAFR  ENSG00000169403          PTAFR  ENSG00000169403   
MARCKSL1            MARCKSL1  ENSG00000175130       MARCKSL1  ENSG00000175130   
CSF3R                  CSF3R  ENSG00000119535          CSF3R  ENSG00000119535   
ZC3H12A              ZC3H12A  ENSG00000163874        ZC3H12A  ENSG00000163874   
PTCH2                  PTCH2  ENSG00000117425          PTCH2  ENSG00000117425   
NEXN                    NEXN  ENSG00000162614           NEXN  ENSG00000162614   
RP11-386I14.4  RP11-386I14.4  ENSG00000273338  RP11-386I14.4  ENSG00000273338   
IFI44L                IFI44L  ENSG00000137959         IFI44L  ENSG00000137959   
...                      ...              ...            ...              ...   
LGALS1                LGALS1  ENSG00000100097         LGALS1  ENSG00000100097   
MAFF                    MAFF  ENSG00000185022           MAFF  ENSG00000185022   
APOBEC3A            APOBEC3A  ENSG00000128383       APOBEC3A  ENSG00000128383   
APOBEC3G            APOBEC3G  ENSG00000239713       APOBEC3G  ENSG00000239713   
TNFRSF13C          TNFRSF13C  ENSG00000159958      TNFRSF13C  ENSG00000159958   
NFAM1                  NFAM1  ENSG00000235568          NFAM1  ENSG00000235568   
RNU12                  RNU12  ENSG00000270022          RNU12  ENSG00000270022   
TSPO                    TSPO  ENSG00000100300           TSPO  ENSG00000100300   
FAM118A              FAM118A  ENSG00000100376        FAM118A  ENSG00000100376   
TTC38                  TTC38  ENSG00000075234          TTC38  ENSG00000075234   
PLXNB2                PLXNB2  ENSG00000196576         PLXNB2  ENSG00000196576   
TYMP                    TYMP  ENSG00000025708           TYMP  ENSG00000025708   
ODF3B                  ODF3B  ENSG00000177989          ODF3B  ENSG00000177989   
CH507-513H4.6  CH507-513H4.6  ENSG00000280800  CH507-513H4.6  ENSG00000280800   
CH507-513H4.3  CH507-513H4.3  ENSG00000281181  CH507-513H4.3  ENSG00000281181   
MIR155HG            MIR155HG  ENSG00000234883       MIR155HG  ENSG00000234883   
APP                      APP  ENSG00000142192    

In [8]:
anndata.obs

Sample  n_counts  n_genes batch louvain  \
index                                                                  
data_3p-AAACCTGAGCATCATC-0  data_3p    2394.0      871     0       9   
data_3p-AAACCTGAGCTAGTGG-0  data_3p    4520.0     1316     0       5   
data_3p-AAACCTGCACATTAGC-0  data_3p    2788.0      898     0       1   
data_3p-AAACCTGCACTGTTAG-0  data_3p    4667.0     1526     0       0   
data_3p-AAACCTGCATAGTAAG-0  data_3p    4440.0     1495     0       0   
data_3p-AAACCTGCATGAACCT-0  data_3p    3224.0     1253     0       7   
data_3p-AAACCTGGTAAGAGGA-0  data_3p    5205.0     1433     0       4   
data_3p-AAACCTGGTAGAAGGA-0  data_3p    5493.0     1632     0       0   
data_3p-AAACCTGGTCCAGTGC-0  data_3p    4419.0     1134     0       4   
data_3p-AAACCTGGTGTCTGAT-0  data_3p    3343.0     1176     0       5   
data_3p-AAACCTGGTTTGCATG-0  data_3p    6360.0     1900     0       0   
data_3p-AAACCTGGTTTGTTTC-0  data_3p    5189.0     1548     0       4   
data_3p-AAACCTGTCCGTTGCT-0  data_3p    4864.0     1367     0      12   
data_3p-AAACCTGTCCTGTAGA-0  data_3p    3580.0     1390     0      13   
data_3p-AAACCTGTCGCCAAAT-0  data_3p    5617.0     1414     0       1   
data_3p-AAACCTGTCGTGGACC-0  data_3p    4591.0     1324     0      23   
data_3p-AAACCTGTCTACCAGA-0  data_3p    3592.0     1174     0       4   
data_3p-AAACCTGTCTCAAGTG-0  data_3p    5496.0     1607     0       5   
data_3p-AAACCTGTCTCGCTTG-0  data_3p    6218.0     1768     0       0   
data_3p-AAACCTGTCTGCGGCA-0  data_3p    3401.0     1132     0       4   
data_3p-AAACGGGAGCCTCGTG-0  data_3p    9267.0     2214     0      21   
data_3p-AAACGGGAGGTGTGGT-0  data_3p    3509.0      958     0       4   
data_3p-AAACGGGAGTACGATA-0  data_3p    3567.0     1333     0      20   
data_3p-AAACGGGCACCTCGGA-0  data_3p    2752.0     1035     0       9   
data_3p-AAACGGGCACGAAACG-0  data_3p    3512.0     1151     0       4   
data_3p-AAACGGGCAGTAAGAT-0  data_3p    2907.0     1001     0       9   
data_3p-AAACGGGGTACAGTTC-0  data_3p    3468.0     1478     0      15   
data_3p-AAACGGGGTACCCAAT-0  data_3p    5529.0     1714     0      12   
data_3p-AAACGGGGTAGCTTGT-0  data_3p    3457.0      947     0       1   
data_3p-AAACGGGGTGCGCTTG-0  data_3p    3751.0     1155     0       1   
...                             ...       ...      ...   ...     ...   
data_5p-TTTGGTTAGGATGCGT-1  data_5p    8723.0     2585     1      14   
data_5p-TTTGGTTCAAGGTGTG-1  data_5p    8769.0     2430     1       2   
data_5p-TTTGGTTCACAAGACG-1  data_5p    6255.0     1890     1      11   
data_5p-TTTGGTTCAGTGACAG-1  data_5p    5228.0     2030     1      15   
data_5p-TTTGGTTCATTTGCCC-1  data_5p    3154.0     1200     1      10   
data_5p-TTTGGTTGTAAGTGTA-1  data_5p    2268.0      996     1      17   
data_5p-TTTGGTTGTCAAAGCG-1  data_5p   12826.0     3327     1       8   
data_5p-TTTGGTTGTCGAACAG-1  data_5p    3181.0     1378     1      26   
data_5p-TTTGGTTGTTATGCGT-1  data_5p    5792.0     2056     1       6   
data_5p-TTTGGTTGTTATTCTC-1  data_5p    3453.0     1566     1      19   
data_5p-TTTGGTTTCGTTGACA-1  data_5p    5738.0     1674     1       2   
data_5p-TTTGGTTTCTCACATT-1  data_5p    4206.0     1900     1      19   
data_5p-TTTGGTTTCTCGAGTA-1  data_5p    4368.0     1560     1      16   
data_5p-TTTGGTTTCTGCTTGC-1  data_5p    3425.0     1338     1       6   
data_5p-TTTGTCAAGAAACCTA-1  data_5p    5438.0     1974     1       2   
data_5p-TTTGTCAAGACCTAGG-1  data_5p    4627.0     1799     1      19   
data_5p-TTTGTCAAGAGCCCAA-1  data_5p    4160.0     1355     1      11   
data_5p-TTTGTCAAGGAATGGA-1  data_5p    5149.0     1867     1      16   
data_5p-TTTGTCAAGTCGAGTG-1  data_5p    2568.0     1011     1       2   
data_5p-TTTGTCACACATCCAA-1  data_5p    6317.0     2117     1       3   
data_5p-TTTGTCACAGCTGGCT-1  data_5p    4788.0     1684     1      16   
data_5p-TTTGTCACAGGTGGAT-1  data_5p    5390.0     1410     1      11   
data_5p-TTTGTCAGTCCGAAGA-1  data_5p    5857.0     1792     1       2 

In [9]:
x = np.array([
    [1,2,3],
    [10, 11, 12]
])
x

array([[ 1,  2,  3],
       [10, 11, 12]])

In [10]:
x.shape

(2, 3)

In [11]:
x[1] = [21, 22, 23]
x

array([[ 1,  2,  3],
       [21, 22, 23]])